- name: send completion notification to Discord
  tags: always
  community.general.discord:
    webhook_id: "{{id}}"
    webhook_token: "{{token}}"
    content: "✔️  Fortigate Backup Finished *{{inventory_hostname}}*"
  changed_when: False
